export interface TechIcon {
	icon: string
	color: string
}

// Generated by V0
export const techIconMap: Record<string, TechIcon> = {
	go: { icon: "go", color: "#00ADD8" },
	"springboot": { icon: "springboot", color: "#6DB33F" },
	golang: { icon: "go", color: "#00ADD8" },
	grafana: { icon: "grafana", color: "#F46800" },
	rabbitmq: { icon: "rabbitmq", color: "#FF6600" },
	postgresql: { icon: "postgresql", color: "#4169E1" },
	postgres: { icon: "postgresql", color: "#4169E1" },
	redis: { icon: "redis", color: "#DC382D" },
	docker: { icon: "docker", color: "#2496ED" },
	kubernetes: { icon: "kubernetes", color: "#326CE5" },
	typescript: { icon: "typescript", color: "#3178C6" },
	javascript: { icon: "javascript", color: "#F7DF1E" },
	python: { icon: "python", color: "#3776AB" },
	rust: { icon: "rust", color: "#000000" },
	java: { icon: "openjdk", color: "#007396" },
	"c++": { icon: "cplusplus", color: "#00599C" },
	mongodb: { icon: "mongodb", color: "#47A248" },
	mysql: { icon: "mysql", color: "#4479A1" },
	"digitalocean": { icon: "digitalocean", color: "#0080FF" },
	discord: { icon: "discord", color: "#5865F2" },
	graphql: { icon: "graphql", color: "#E10098" },
	angular: { icon: "angular", color: "#DD1100" },
	react: { icon: "react", color: "#61DAFB" },
	node: { icon: "nodedotjs", color: "#339933" },
	"node.js": { icon: "nodedotjs", color: "#339933" },
	html: { icon: "html5", color: "#E34F26" },
	nodejs: { icon: "nodedotjs", color: "#339933" },
	svelte: { icon: "svelte", color: "#FF3E00" },
	vue: { icon: "vuedotjs", color: "#4FC08D" },
	nextjs: { icon: "nextdotjs", color: "#000000" },
	"next.js": { icon: "nextdotjs", color: "#000000" },
	tailwind: { icon: "tailwindcss", color: "#06B6D4" },
	tailwindcss: { icon: "tailwindcss", color: "#06B6D4" },
	aws: { icon: "amazonaws", color: "#FF9900" },
	gcp: { icon: "googlecloud", color: "#4285F4" },
	azure: { icon: "microsoftazure", color: "#0078D4" },
	vercel: { icon: "vercel", color: "#000000" },
	github: { icon: "github", color: "#181717" },
	css: { icon: "css", color: "#663399" },
	gitlab: { icon: "gitlab", color: "#FC6D26" },
	nginx: { icon: "nginx", color: "#009639" },
	express: { icon: "express", color: "#000000" },
	fastapi: { icon: "fastapi", color: "#009688" },
	django: { icon: "django", color: "#092E20" },
	flask: { icon: "flask", color: "#000000" },
	lua: { icon: "lua", color: "#000080" },
	neovim: { icon: "neovim", color: "#57A143" },
	kafka: { icon: "apachekafka", color: "#231F20" },
	prisma: { icon: "prisma", color: "#2D3748" },
	supabase: { icon: "supabase", color: "#3ECF8E" },
}

export function getTechIcon(tech: string): TechIcon | null {
	const normalized = tech.toLowerCase().replace(/\s+/g, "");
	return techIconMap[normalized] || null;
}

export function getTechInitials(tech: string): string {
	const words = tech.split(/[\s-_]+/)
	if (words.length === 1) {
		return tech.substring(0, 2).toUpperCase()
	}
	return words
		.slice(0, 2)
		.map((w) => w[0])
		.join("")
		.toUpperCase()
}
